//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItStepAcademyTest.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class itsteptestEntities : DbContext
    {
        public itsteptestEntities()
            : base("name=itsteptestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<comments> comments { get; set; }
        public DbSet<groups> groups { get; set; }
        public DbSet<messages> messages { get; set; }
        public DbSet<questions> questions { get; set; }
        public DbSet<results> results { get; set; }
        public DbSet<roles> roles { get; set; }
        public DbSet<subjects> subjects { get; set; }
        public DbSet<tests> tests { get; set; }
        public DbSet<users> users { get; set; }
        public DbSet<variants> variants { get; set; }
    }
}
