//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItStepAcademyTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class variants
    {
        public int id { get; set; }
        public string text { get; set; }
        public int @true { get; set; }
        public int question { get; set; }
    }
}
